var mongoose = require('mongoose');

// Initialize Model Schema's
var employeeSchema = mongoose.Schema({
  employee_id: Number,
  govt_id: String,
  first_name: String,
  middle_name: String,
  second_name: String,
  last_name: String,
  ics_position: String,
  incident_position: String,
  dob: Date,
  phone_number: Number,
  phone_number_2: Number,
  phone_number_3: Number,
  email: String,
  ssn: String,
  address: String,
  city: String,
  state: String,
  zip: Number,
  is_active: Boolean,
  picture: String,
  gender: String,
  sawyer: String,
  exp: String,
  mspa_number: String,
  mspa_exp_date: Date,
  dl_number: Number,
  dl_exp_date: Date,
  dl_state: String,
  id_2: String,
  contact_1_name: String,
  contact_1_phone: Number,
  contact_1_relation: String,
  contact_2_name: String,
  contact_2_phone: Number,
  contact_2_relation: String,
  updated_at: Date,
  created_at: Date
});

module.exports = mongoose.model('Employee', employeeSchema);



//// DATA STRUCTURE FOR EMPLOYEE
//{
//  _id: ObjectId("514d461b203b7975a0ecb9a2"),
//  employee_id: 19102,
//  govt_id: "ICA110439",
//  first_name: "Dana",
//  middle_name: null,
//  second_name: null,
//  last_name: "Hartley",
//  ics_position: "FFT-1/ICT5",
//  incident_position: "FFT-1 / ICT5",
//  dob: "3/4/88 0:00",
//  phone_number: 6033598416,
//  phone_number_2: null,
//  phone_number_3: null,
//  email: "test@gmail.com",
//  ssn: "xxx-xx-xxxx",
//  address: "551 random st",
//  city: "Monroe",
//  state: "OR",
//  zip: 97456,
//  is_active: true,
//  picture: "http://retroavatar.appspot.com/api?name=",
//  gender: "Male",
//  sawyer: "B",
//  exp: null,
//  mspa_number: "E-09-809102-F-14-R",
//  mspa_exp_date: "6/30/14 0:00",
//  dl_number: 3589798,
//  dl_exp_date: null,
//  dl_state: "OR",
//  id_2: null,
//  contact_1_name: "Ernest Hartley",
//  contact_1_phone: 6033593958,
//  contact_1_relation: "Father",
//  contact_2_name: null,
//  contact_2_phone: null,
//  contact_2_relation: null,
//  updated_at: "7/5/05 0:00",
//  created_at: null
//}